### PR TITLE
fix: landing page improvements

### LINKED ISSUE #10: Landing page improvements
- overall smaller components
- remove  red diamond-shaped bullets

### PR DESCRIPTION
**Pull request by adarshajit**
This PR fixes #10
- Fixed the font size of the landing page; made sure it is following the same size throughout.
- Removed the bullet point within the cards, since it was not blending well with the text.

### CODE REVIEW

File: components/Landing/Creators.tsx [hunk 1]
```diff
@@ -43,7 +43,7 @@ export const Creators: React.FC = () => {
           >
             Creators
           </Heading>
-          <Box>
+          <Box flexDir="column" fontSize={{ base: 'md', md: '2xl' }} mb={10}>
```
Comment (dan13ram) [inline components/Landing/Creators.tsx:46]:
```suggestion
          <Box fontSize={{ base: 'md', md: '2xl' }} mb={10}>
```
`flexDir` doesn't do anything for `Box` component if we are not also setting `display="flex"`

**Review by dan13ram — COMMENTED** [review]
Can you rebase with `dev`, there was an issue earlier where deploy previews weren't working.

File: components/Landing/QuestChains.tsx [hunk 2]
```diff
@@ -18,7 +18,7 @@ export const QuestChains: React.FC = () => {
       w="full"
       align="center"
       justify="center"
-      minH="80vh"
+      minH="100vh"
```
Comment (dan13ram) [inline components/Landing/QuestChains.tsx:21]: we want this to be 80vh only, so that the whole illustration as well as a portion of the "what are we building" is seen. This is so that the user knows there is something to scroll down to.

File: components/Landing/Creators.tsx [hunk 3]
```diff
@@ -73,26 +73,31 @@ export const Creators: React.FC = () => {
             "empty1 admins empty2 empty2"
           `,
         }}
+        fontSize={{ base: 'md', md: '2xl' }}
       >
         {!isSmallScreen && (
-          <Box h="338px" gridArea="creators" pr={12}>
+          <Box h="338px" gridArea="creators" mb={40} mr={10}>
```
Comment (dan13ram) [inline components/Landing/Creators.tsx:79]: here as you can see the "reviwers" block needs to be linked to the other roles
Screenshot from 2022-10-24 21:20:41

**Review by dan13ram — CHANGES_REQUESTED** [review]
Apologies for the delay in review 🙏🏽 
Thanks for your first PR @adarshajit! Other than these 2 small changes, this looks good.

**Comment by dan13ram** [comment]
I also think we can make some more modifications to make the landing page better. 

- Overall can reduce the fontsizes for both mobile and desktop.
- Currently its not optimized well for mobile. For example, each block below can be made much smaller, and also the order should be "reviewers < editors < admins < owners"
Screenshot from 2022-10-24 21:27:34

**Comment by vidvidvid** [comment]
@adarshajit u still there? could you wrap up this pr? :)

**Comment by vidvidvid** [comment]
Np, we've all been :D

File: components/Landing/QuestChains.tsx (hunk 2 above)
Comment (vidvidvid) [reply components/Landing/QuestChains.tsx:21]: seems like a good idea! @davort ?

Comment (vidvidvid) [reply components/Landing/QuestChains.tsx:21]: however, i don't think we have to put too much effort/time into the upgrades of this site since we're planning to make a new animated landing page soon anyway.

Comment (vidvidvid) [reply components/Landing/QuestChains.tsx:21]: something like this could work as well: 
Screenshot 2022-10-30 at 11 32 42

**Comment by vidvidvid** [comment]
@adarshajit thank you very much for getting back to this issue. could you take care of one more little thing, please? the `learn more` button doesn't take the user to the second page, although the cursor suggests there should be an action when clicking on it. could you either add the action or change the cursor styling? (preferably add the action :P)

**Review by vidvidvid — APPROVED** [review]
beautiful! :)
